name: example

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'
    
jobs:
  build: # job_id
    runs-on: ubuntu-latest
    
    steps:
      - name: repo checkout  # загрузка содержимого корня репозитория на вирт машину
        uses: actions/checkout@v4  
      - name: list current folder
        run: ls
      - name: Run script
        run: test.py
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build
