name: example

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'
    
jobs:
  build: # job_id
    runs-on: ubuntu-latest
    
    steps:
      - name: repo checkout  # загрузка содержимого корня репозитория на вирт машину
        uses: actions/checkout@v4  
        # with:
        #   sparse-checkout: |
        #     test.py    # загрузка только этого файла
      - name: list current folder
        run: ls
      - name: Run script
        run: python test.py
      - name: Deploy  # deploy происходит из ветки gh-pages (созданной action и указанной в settings), 
                      # в которую размещается папка build, созданная на runner посредством test.py
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
